CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  userName VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE searches (
  id SERIAL PRIMARY KEY,
  searchTerm VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE user_searches (
  id SERIAL PRIMARY KEY,
  search_id INTEGER REFERENCES searches (id) NOT NULL,
  user_id INTEGER REFERENCES users (id) NOT NULL
);